export const SET_LOG_USER = 'DASHBOARD/SET_LOG_USER'
export const SET_PROFILE_ID = 'DASHBOARD/SET_PROFILE_ID'
export const SET_MOVIES = 'DASHBOARD/SET_MOVIES'
export const SET_GENRE_ID = 'DASHBOARD/SET_GENRE_ID'
