export const SET_LOG_USER = 'DASHBOARD/SET_LOG_USER'
export const SET_PROFILE_ID = 'DASHBOARD/SET_PROFILE_ID'
export const SET_WATCHED = 'DASHBOARD/SET_WATCHED'
export const SET_WATCHLIST = 'DASHBOARD/SET_WATCHLIST'
